name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  acronym: upld
  environment: dev
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout solution
      uses: actions/checkout@v2
      
    - name: Setup Enviroment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test units
      run: dotnet test --no-build --no-restore --configuration Release --output ./output

    - name: Login at Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Create resource group
      uses: Azure/cli@1.0.4
      with:
        inlineScript:
          az group create -n rg${{env.environment}}${{env.acronym}}${{github.run_number}} -l brazilsouth
        
    - name: Create Function App
      uses: Azure/arm-deploy@1.0.3
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: rg${{env.environment}}${{env.acronym}}${{github.run_number}}
        template: ./iac/function-app.json
        parameters: buildNumber=${{ github.run_number }}
        
    - name: Deploy Function App
      uses: Azure/functions-action@v1.3.2
      with:
        app-name: fa${{env.environment}}${{env.acronym}}${{github.run_number}}
        package: ./output